name: Deployment

on:
  push:
    branches:
      - master
env:
  API_URL: ${{ vars.API_URL }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
